### ISSUE TITLE
Boostd panics after a few hours

### ISSUE THREAD

**Issue by stuberman** [filecoin-project/boost#1006]
### Checklist

- [X] This is **not** a question or a support request. If you have any boost related questions, please ask in the [discussion forum](https://github.com/filecoin-project/boost/discussions).
- [X] This is **not** a new feature or enhancement request. If it is, please open a [new idea discussion](https://github.com/filecoin-project/boost/discussions/new?category=ideas) instead. New feature and enhancement requests would be entertained by the boost team after a thorough discussion only.
- [X] I **have** searched on the [issue tracker](https://github.com/filecoin-project/boost/issues) and the [discussion forum](https://github.com/filecoin-project/boost/discussions), and there is no existing related issue or discussion.
- [X] I am running the [`Latest release`](https://github.com/filecoin-project/boost/releases), or the most recent RC(release canadiate) for the upcoming release or the dev branch(master), or have an issue updating to any of these.
- [X] I did not make any code changes to boost.

### Boost component

- [X] boost daemon - storage providers
- [ ] boost client
- [ ] boost UI
- [ ] boost data-transfer
- [ ] boost index-provider
- [ ] Other

### Boost Version

```text
lotus-miner version
Daemon: 1.19.0-rc2+mainnet+git.2520b1644+api1.5.0
Local: lotus-miner version 1.19.0-rc2+mainnet+git.2520b1644

boostd -version
boostd version 1.5.1-rc1+git.f3fd05a
```

### Describe the Bug

After upgrading Lotus and Boost I see a boostd panic after a few hours. see log below

Here is the start string I use
`nohup boostd run --pprof >> /market/logs/boost.log 2>&1 &`

### Logging Information

```text
2022-11-24T15:20:09.965Z	ERROR	retrieval	impl/provider.go:434	Retrieval query: GetAsk: GetRetrievalPricingInput: failed to fetch storage deal state: 1 error occurred:
	* deal 7841268 not found - deal may not have completed sealing before deal proposal start epoch, or deal may have been slashed


2022-11-24T15:20:10.089Z	ERROR	retrieval	impl/provider.go:434	Retrieval query: GetAsk: GetRetrievalPricingInput: failed to fetch storage deal state: 1 error occurred:
	* deal 7841268 not found - deal may not have completed sealing before deal proposal start epoch, or deal may have been slashed


panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x1a173c0]

goroutine 81 [running]:
github.com/filecoin-project/boost/retrievalmarket/rtvllog.(*RetrievalLog).OnValidationEvent(0xc016ee02a0, {0x1, {0xc017bced80, 0x26}, 0xc0b59dc1e0, {{0xc01afcf290, 0x24}}, {0x4477860, 0xc0b58fa580}, 0x0, ...})
	/home/stuart/boost/retrievalmarket/rtvllog/retrieval_log.go:51 +0x80
github.com/filecoin-project/go-fil-markets/retrievalmarket/impl/requestvalidation.queryValidationDispatcher({0x3aedae0?, 0xc02fa6e5a0?}, {0x384b540?, 0xc00f7bde00?})
	/home/stuart/go/pkg/mod/github.com/filecoin-project/go-fil-markets@v1.25.1/retrievalmarket/impl/requestvalidation/requestvalidation.go:226 +0x155
github.com/hannahhoward/go-pubsub.(*PubSub).Publish(0xc016fc57c0, {0x3aedae0, 0xc02fa6e5a0})
	/home/stuart/go/pkg/mod/github.com/hannahhoward/go-pubsub@v0.0.0-20200423002714-8d62886cc36e/pubsub.go:76 +0x12d
github.com/filecoin-project/go-fil-markets/retrievalmarket/impl/requestvalidation.(*ProviderRequestValidator).ValidatePull(0xc016dc6930, 0x1, {{0x3884ba0, 0x17}, {0xc0acf42db8, 0x690f25}, 0x38f8e80}, {0xc017bced80, 0x26}, {0x444a220, ...}, ...)
	/home/stuart/go/pkg/mod/github.com/filecoin-project/go-fil-markets@v1.25.1/retrievalmarket/impl/requestvalidation/requestvalidation.go:81 +0x405
github.com/filecoin-project/go-data-transfer/impl.(*manager).validateVoucher(0xc01b3fb050, 0x80?, {{0xc017bced80, 0x26}, {0xc0170c0480, 0x26}, 0x172a87de78480b16}, {0xc017bced80, 0x26}, {0x4478270, ...}, ...)
	/home/stuart/go/pkg/mod/github.com/filecoin-project/go-data-transfer@v1.15.2/impl/events.go:490 +0x209
github.com/filecoin-project/go-data-transfer/impl.(*manager).restartRequest(0xc01b3fb050, {{0xc017bced80, 0x26}, {0xc0170c0480, 0x26}, 0x172a87de78480b16}, {0x4478270, 0xc057804700})
	/home/stuart/go/pkg/mod/github.com/filecoin-project/go-data-transfer@v1.15.2/impl/events.go:379 +0x2ff
github.com/filecoin-project/go-data-transfer/impl.(*manager).receiveRestartRequest(0xc01b3f3f50?, {{0xc017bced80, 0x26}, {0xc0170c0480, 0x26}, 0x172a87de78480b16}, {0x4478270, 0xc057804700})
	/home/stuart/go/pkg/mod/github.com/filecoin-project/go-data-transfer@v1.15.2/impl/events.go:343 +0x14e
github.com/filecoin-project/go-data-transfer/impl.(*manager).OnRequestReceived(0xc01b3fb050, {{0xc017bced80, 0x26}, {0xc0170c0480, 0x26}, 0x172a87de78480b16}, {0x4478270, 0xc057804700})
	/home/stuart/go/pkg/mod/github.com/filecoin-project/go-data-transfer@v1.15.2/impl/events.go:166 +0x488
github.com/filecoin-project/go-data-transfer/transport/graphsync.(*Transport).gsReqRecdHook(0xc01b3aa6e0, {0xc017bced80, 0x26}, {0x446add0?, 0xc087881770}, {0x44692d0, 0xc01e73fa70})
	/home/stuart/go/pkg/mod/github.com/filecoin-project/go-data-transfer@v1.15.2/transport/graphsync/graphsync.go:609 +0x374
github.com/ipfs/go-graphsync/responsemanager/hooks.requestHookDispatcher({0x39f78a0?, 0xc0b6388b40?}, {0x38a7f60?, 0xc0022bc090?})
	/home/stuart/go/pkg/mod/github.com/ipfs/go-graphsync@v0.13.1/responsemanager/hooks/requesthook.go:72 +0xd9
github.com/hannahhoward/go-pubsub.(*PubSub).Publish(0xc01b3a1600, {0x39f78a0, 0xc0b6388b40})
	/home/stuart/go/pkg/mod/github.com/hannahhoward/go-pubsub@v0.0.0-20200423002714-8d62886cc36e/pubsub.go:76 +0x12d
github.com/ipfs/go-graphsync/responsemanager/hooks.(*IncomingRequestHooks).ProcessRequestHooks(0xc01b393458, {0xc017bced80, 0x26}, {0x446add0, 0xc087881770})
	/home/stuart/go/pkg/mod/github.com/ipfs/go-graphsync@v0.13.1/responsemanager/hooks/requesthook.go:104 +0x133
github.com/ipfs/go-graphsync/responsemanager.(*queryPreparer).prepareQuery(0xc0acf43a48, {0x4461e68, 0xc01be07bc0}, {0xc017bced80, 0x26}, {{{0xc01afcf4d0, 0x24}}, {0x4477860, 0xc0c8915bc0}, 0x0, ...}, ...)
	/home/stuart/go/pkg/mod/github.com/ipfs/go-graphsync@v0.13.1/responsemanager/querypreparer.go:47 +0xd9
github.com/ipfs/go-graphsync/responsemanager.(*ResponseManager).taskDataForKey(0xc0003f0d80, {{0xc0b18a7860?, 0xc03e34dc10?}})
	/home/stuart/go/pkg/mod/github.com/ipfs/go-graphsync@v0.13.1/responsemanager/server.go:268 +0x3b9
github.com/ipfs/go-graphsync/responsemanager.(*ResponseManager).startTask(0xc0003f0d80, 0xc033cec600, {0xc01c327920, 0x6d0ec5?})
	/home/stuart/go/pkg/mod/github.com/ipfs/go-graphsync@v0.13.1/responsemanager/server.go:297 +0x9f
github.com/ipfs/go-graphsync/responsemanager.(*startTaskRequest).handle(0xc0b58fa560, 0xc0003f0d80)
	/home/stuart/go/pkg/mod/github.com/ipfs/go-graphsync@v0.13.1/responsemanager/messages.go:123 +0x4f
github.com/ipfs/go-graphsync/responsemanager.(*ResponseManager).run(0xc0003f0d80)
	/home/stuart/go/pkg/mod/github.com/ipfs/go-graphsync@v0.13.1/responsemanager/server.go:43 +0x85
created by github.com/ipfs/go-graphsync/responsemanager.(*ResponseManager).Startup
	/home/stuart/go/pkg/mod/github.com/ipfs/go-graphsync@v0.13.1/responsemanager/client.go:276 +0x56
```

### Repo Steps

1. Run '...'
2. Do '...'
3. See error '...'
...

**Comment by jacobheun** [comment]
Thanks for testing the RC and reporting! ❤️  We're working on a fix and will cut another RC once that's ready.

**Comment by stuberman** [comment]
Here is the output of pprof - I changed the externsion from .output to .output.log to accomodate GitHub restrictions
[dump.output.log](https://github.com/filecoin-project/boost/files/10086126/dump.output.log)
