### ISSUE TITLE
New boostd commit dies

### ISSUE THREAD

**Issue by stuberman** [filecoin-project/boost#1360]
### Checklist

- [X] This is **not** a question or a support request. If you have any boost related questions, please ask in the [discussion forum](https://github.com/filecoin-project/boost/discussions).
- [X] This is **not** a new feature request. If it is, please file a [feature request](https://github.com/filecoin-project/boost/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Ffeature&template=feature_request.yml) instead.
- [X] This is **not** an enhancement request. If it is, please file a [improvement suggestion](https://github.com/filecoin-project/boost/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Fenhancement&template=enhancement.yml) instead.
- [X] I **have** searched on the [issue tracker](https://github.com/filecoin-project/boost/issues) and the [discussion forum](https://github.com/filecoin-project/boost/discussions), and there is no existing related issue or discussion.
- [X] I am running the [`Latest release`](https://github.com/filecoin-project/boost/releases), or the most recent RC(release canadiate) for the upcoming release or the dev branch(master), or have an issue updating to any of these.
- [X] I did not make any code changes to boost.

### Boost component

- [X] boost daemon - storage providers
- [ ] boost client
- [ ] boost UI
- [ ] boost data-transfer
- [ ] boost index-provider
- [ ] Other

### Boost Version

```text
boostd version 1.7.0-rc1+git.ac6f82e

Used with Lotus v1.20.4
```

### Describe the Bug

Boost randomly crashes while processing deals

> ID        Sector  Worker    Hostname  Task  State     Time
> 3d17a5b7  6168    f8d56955  sealer    PC1   running   2h18m16.1s
> 7509a359  6163    f8d56955  sealer    C2    running   47m34.5s
> 75a813c3  6169    f8d56955  sealer    PC1   running   23m1.3s
> 00000000  6166    f8d56955  sealer    PC2   prepared  32m27s

### Logging Information

```text
2023-04-08T23:15:38.480Z	INFO	boost-storage-deal	logs/log.go:40	current sealing state	{"id": "bb7ba56a-64a9-4293-ac58-2b5c97d8c056", "state": "PreCommit2"}
2023-04-08T23:15:39.494Z	INFO	boost-storage-deal	logs/log.go:40	current sealing state	{"id": "4e1b77d6-98b6-49d3-85e4-a95a80c44185", "state": "PreCommit2"}
2023-04-08T23:15:39.556Z	INFO	boost-storage-deal	logs/log.go:40	current sealing state	{"id": "964c68d1-0d2e-4d30-b190-c03228631a3e", "state": "PreCommit2"}
2023-04-08T23:15:40.027Z	INFO	boost-storage-deal	logs/log.go:40	current sealing state	{"id": "86987932-4c32-4c3f-8e00-4007fe42dbd3", "state": "PreCommit2"}
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0xf07fc0ca07a pc=0x75022a]

runtime stack:
runtime.throw({0x4c448a1?, 0x0?})
	/usr/local/go/src/runtime/panic.go:1047 +0x5d fp=0x7f0830ffc6c8 sp=0x7f0830ffc698 pc=0x7679dd
runtime.sigpanic()
	/usr/local/go/src/runtime/signal_unix.go:819 +0x369 fp=0x7f0830ffc718 sp=0x7f0830ffc6c8 pc=0x77e529
runtime.markBits.isMarked(...)
	/usr/local/go/src/runtime/mbitmap.go:272
runtime.greyobject(0xc02c552540, 0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
	/usr/local/go/src/runtime/mgcmark.go:1483 +0x8a fp=0x7f0830ffc768 sp=0x7f0830ffc718 pc=0x75022a
runtime.scanobject(0xc00007e140?, 0xc00007e140)
	/usr/local/go/src/runtime/mgcmark.go:1339 +0x1b2 fp=0x7f0830ffc800 sp=0x7f0830ffc768 pc=0x74fd52
runtime.gcDrain(0xc00007e140, 0x7)
	/usr/local/go/src/runtime/mgcmark.go:1103 +0x1d4 fp=0x7f0830ffc860 sp=0x7f0830ffc800 pc=0x74f574
runtime.gcBgMarkWorker.func2()
	/usr/local/go/src/runtime/mgc.go:1327 +0x6d fp=0x7f0830ffc8b0 sp=0x7f0830ffc860 pc=0x74bc2d
runtime.systemstack()
	/usr/local/go/src/runtime/asm_amd64.s:492 +0x49 fp=0x7f0830ffc8b8 sp=0x7f0830ffc8b0 pc=0x79a409

goroutine 34 [GC worker (idle)]:
runtime.systemstack_switch()
	/usr/local/go/src/runtime/asm_amd64.s:459 fp=0xc00008a750 sp=0xc00008a748 pc=0x79a3a0
runtime.gcBgMarkWorker()
	/usr/local/go/src/runtime/mgc.go:1295 +0x205 fp=0xc00008a7e0 sp=0xc00008a750 pc=0x74b905
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1594 +0x1 fp=0xc00008a7e8 sp=0xc00008a7e0 pc=0x79c5c1
created by runtime.gcBgMarkStartWorkers
	/usr/local/go/src/runtime/mgc.go:1159 +0x25

goroutine 1 [chan receive, 196 minutes]:
runtime.gopark(0xc000800400?, 0x1?, 0xd0?, 0xba?, 0xc0007fb650?)
	/usr/local/go/src/runtime/proc.go:363 +0xd6 fp=0xc01aff55b8 sp=0xc01aff5598 pc=0x76a6b6
runtime.chanrecv(0xc0154bdaa0, 0x0, 0x1)
	/usr/local/go/src/runtime/chan.go:583 +0x49b fp=0xc01aff5648 sp=0xc01aff55b8 pc=0x7341fb
runtime.chanrecv1(0xc001e0c1e0?, 0xc0231f1200?)
	/usr/local/go/src/runtime/chan.go:442 +0x18 fp=0xc01aff5670 sp=0xc01aff5648 pc=0x733cf8
main.glob..func36(0x7c64c80?)
	/home/stuart/boost/cmd/boostd/run.go:157 +0x1199 fp=0xc01aff5988 sp=0xc01aff5670 pc=0x28f4b59
github.com/urfave/cli/v2.(*Command).Run(0x7c64c80, 0xc001af35c0, {0xc00071b710, 0x1, 0x1})
	/home/stuart/go/pkg/mod/github.com/urfave/cli/v2@v2.24.4/command.go:273 +0xa42 fp=0xc01aff5c18 sp=0xc01aff5988 pc=0x146cc42
github.com/urfave/cli/v2.(*Command).Run(0xc0006c3080, 0xc001af33c0, {0xc000052040, 0x2, 0x2})
	/home/stuart/go/pkg/mod/github.com/urfave/cli/v2@v2.24.4/command.go:266 +0xc97 fp=0xc01aff5ea8 sp=0xc01aff5c18 pc=0x146ce97
github.com/urfave/cli/v2.(*App).RunContext(0xc001afa3c0, {0x5c415d8?, 0xc000056d08}, {0xc000052040, 0x2, 0x2})
	/home/stuart/go/pkg/mod/github.com/urfave/cli/v2@v2.24.4/app.go:332 +0x616 fp=0xc01aff5f18 sp=0xc01aff5ea8 pc=0x14698d6
github.com/urfave/cli/v2.(*App).Run(...)
	/home/stuart/go/pkg/mod/github.com/urfave/cli/v2@v2.24.4/app.go:309
main.main()
	/home/stuart/boost/cmd/boostd/main.go:57 +0x4dd fp=0xc01aff5f80 sp=0xc01aff5f18 pc=0x28f09bd
runtime.main()
	/usr/local/go/src/runtime/proc.go:250 +0x212 fp=0xc01aff5fe0 sp=0xc01aff5f80 pc=0x76a2f2
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1594 +0x1 fp=0xc01aff5fe8 sp=0xc01aff5fe0 pc=0x79c5c1

goroutine 2 [force gc (idle), 197 minutes]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
	/usr/local/go/src/runtime/proc.go:363 +0xd6 fp=0xc000088fb0 sp=0xc000088f90 pc=0x76a6b6
runtime.goparkunlock(...)
	/usr/local/go/src/runtime/proc.go:369
runtime.forcegchelper()
	/usr/local/go/src/runtime/proc.go:302 +0xad fp=0xc000088fe0 sp=0xc000088fb0 pc=0x76a54d
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1594 +0x1 fp=0xc000088fe8 sp=0xc000088fe0 pc=0x79c5c1
created by runtime.init.6
	/usr/local/go/src/runtime/proc.go:290 +0x25

goroutine 3 [GC sweep wait]:
runtime.gopark(0x1?, 0x0?, 0x0?, 0x0?, 0x0?)
	/usr/local/go/src/runtime/proc.go:363 +0xd6 fp=0xc000089790 sp=0xc000089770 pc=0x76a6b6
runtime.goparkunlock(...)
	/usr/local/go/src/runtime/proc.go:369
runtime.bgsweep(0x0?)
	/usr/local/go/src/runtime/mgcsweep.go:297 +0xd7 fp=0xc0000897c8 sp=0xc000089790 pc=0x754a57
runtime.gcenable.func1()
	/usr/local/go/src/runtime/mgc.go:178 +0x26 fp=0xc0000897e0 sp=0xc0000897c8 pc=0x7496a6
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1594 +0x1 fp=0xc0000897e8 sp=0xc0000897e0 pc=0x79c5c1
created by runtime.gcenable
	/usr/local/go/src/runtime/mgc.go:178 +0x6b
```

### Repo Steps

1. Run '...'
2. Do '...'
3. See error '...'
...

**Comment by LexLuthr** [comment]
@stuberman Is this happening regularly? Or was it just once? How long after starting does Boost dies? Is this the full crash log?

**Comment by stuberman** [comment]
It has happened several times since I updated to 1.7

**Comment by stuberman** [comment]
This happens randomly.  It can run for a few hours or a whole day. 

The logs are huge, I only put the first logs after a crash.

**Comment by willscott** [comment]
what version of golang was used to build boost?

**Comment by stuberman** [comment]
I used go v1.19.7

**Comment by willscott** [comment]
Can you try using the current v1.20 and see if you experience it again?

the v1.20 release notes do include:
> The garbage collector behaves less erratically 

although i don't know if that means "we fixed potential panic in the garbage collector"

**Comment by stuberman** [comment]
Will do once I get back home this weekend after ESPA.

**Comment by jacobheun** [comment]
Seeing this on our SP as well, we're going to upgrade to 1.20 and monitor.

**Comment by stuberman** [comment]
Updated to boost v1.7.0 and go v1.20.3
Not seeing this now
