### ISSUE TITLE
The "Awaiting Publish Message" UI causes boost to crash

### ISSUE THREAD

**Issue by LexLuthr** [filecoin-project/boost#1798]
The crash is caused in Elapsed calculation when message is sent
```
2023/11/02 08:32:10 graphql: panic occurred: runtime error: invalid memory address or nil pointer dereference
goroutine 6735815 [running]:
github.com/graph-gophers/graphql-go/log.(*DefaultLogger).LogPanic(0x0?, {0x6a14f30?, 0xc015614480}, {0x4f77820, 0x8e0aab0})
        /home/nonsense/go/pkg/mod/github.com/graph-gophers/graphql-go@v1.3.0/log/log.go:21 +0x65
github.com/graph-gophers/graphql-go/internal/exec.execFieldSelection.func2.1()
        /home/nonsense/go/pkg/mod/github.com/graph-gophers/graphql-go@v1.3.0/internal/exec/exec.go:187 +0x89
panic({0x4f77820, 0x8e0aab0})
        /usr/local/go/src/runtime/panic.go:884 +0x213
github.com/filecoin-project/boost/lib/mpoolmonitor.(*MpoolMonitor).MsgExecElapsedEpochs(0xc00c9b86c0, {0x6a14f68, 0xc015614630}, {{0xc19c83cab0?, 0x1?}})
        /home/nonsense/boost/lib/mpoolmonitor/mpoolmonitor.go:196 +0x185
github.com/filecoin-project/boost/gql.(*dealResolver).message(0xc00eda4800, {0x6a14f68?, 0xc015614630?}, 0xc000b6f660?, {0x881855?, 0x50efec0?, 0x50efec0?})
        /home/nonsense/boost/gql/resolver.go:620 +0x588
github.com/filecoin-project/boost/gql.(*dealResolver).Message(0xc00eda4800, {0x6a14f68?, 0xc015614630?})
        /home/nonsense/boost/gql/resolver.go:574 +0x48
reflect.Value.call({0x540b9a0?, 0xc00eda4800?, 0x8205f6?}, {0x5487e55, 0x4}, {0xc00d3005d0, 0x1, 0x87c72e?})
        /usr/local/go/src/reflect/value.go:586 +0xb0b
reflect.Value.Call({0x540b9a0?, 0xc00eda4800?, 0xc000130720?}, {0xc00d3005d0?, 0x5469aa0?, 0x0?})
        /usr/local/go/src/reflect/value.go:370 +0xbc
github.com/graph-gophers/graphql-go/internal/exec.execFieldSelection.func2(0x0?, {0x6a14f30?, 0xc015614480?}, 0xc00d3005a0, 0xc011473c00, 0xc010e19ec0, {0x6a14f68?, 0xc015614630})
        /home/nonsense/go/pkg/mod/github.com/graph-gophers/graphql-go@v1.3.0/internal/exec/exec.go:211 +0x4c6
github.com/graph-gophers/graphql-go/internal/exec.execFieldSelection({0x6a14f30, 0xc015614480}, 0xc000f31c00, 0x0?, 0xc011473c00, 0x0?, 0x1)
        /home/nonsense/go/pkg/mod/github.com/graph-gophers/graphql-go@v1.3.0/internal/exec/exec.go:231 +0x1ce
github.com/graph-gophers/graphql-go/internal/exec.(*Request).execSelections.func1(0xc011473c00)
        /home/nonsense/go/pkg/mod/github.com/graph-gophers/graphql-go@v1.3.0/internal/exec/exec.go:81 +0x1b8
created by github.com/graph-gophers/graphql-go/internal/exec.(*Request).execSelections
        /home/nonsense/go/pkg/mod/github.com/graph-gophers/graphql-go@v1.3.0/internal/exec/exec.go:77 +0x1d0

context: context.Background.WithCancel.WithCancel.WithValue(type string, val <not Stringer>).WithDeadline(2023-11-02 08:32:11.950743271 -0400 EDT m=+5850.009873342 [989.330027ms])
2023/11/02 08:32:10 graphql: panic occurred: runtime error: invalid memory address or nil pointer dereference
goroutine 6735815 [running]:
github.com/graph-gophers/graphql-go/log.(*DefaultLogger).LogPanic(0xc010e19028?, {0x6a14f30?, 0xc015614480}, {0x4f77820, 0x8e0aab0})
        /home/nonsense/go/pkg/mod/github.com/graph-gophers/graphql-go@v1.3.0/log/log.go:21 +0x65
github.com/graph-gophers/graphql-go/internal/exec.(*Request).handlePanic(0xc000f31c00, {0x6a14f30, 0xc015614480})
        /home/nonsense/go/pkg/mod/github.com/graph-gophers/graphql-go@v1.3.0/internal/exec/exec.go:32 +0x6a
panic({0x4f77820, 0x8e0aab0})
        /usr/local/go/src/runtime/panic.go:884 +0x213
github.com/graph-gophers/graphql-go/internal/exec.execFieldSelection.func2.1()
        /home/nonsense/go/pkg/mod/github.com/graph-gophers/graphql-go@v1.3.0/internal/exec/exec.go:188 +0x96
panic({0x4f77820, 0x8e0aab0})
        /usr/local/go/src/runtime/panic.go:884 +0x213
github.com/filecoin-project/boost/lib/mpoolmonitor.(*MpoolMonitor).MsgExecElapsedEpochs(0xc00c9b86c0, {0x6a14f68, 0xc015614630}, {{0xc19c83cab0?, 0x1?}})
        /home/nonsense/boost/lib/mpoolmonitor/mpoolmonitor.go:196 +0x185
github.com/filecoin-project/boost/gql.(*dealResolver).message(0xc00eda4800, {0x6a14f68?, 0xc015614630?}, 0xc000b6f660?, {0x881855?, 0x50efec0?, 0x50efec0?})
        /home/nonsense/boost/gql/resolver.go:620 +0x588
github.com/filecoin-project/boost/gql.(*dealResolver).Message(0xc00eda4800, {0x6a14f68?, 0xc015614630?})
        /home/nonsense/boost/gql/resolver.go:574 +0x48
reflect.Value.call({0x540b9a0?, 0xc00eda4800?, 0x8205f6?}, {0x5487e55, 0x4}, {0xc00d3005d0, 0x1, 0x87c72e?})
        /usr/local/go/src/reflect/value.go:586 +0xb0b
reflect.Value.Call({0x540b9a0?, 0xc00eda4800?, 0xc000130720?}, {0xc00d3005d0?, 0x5469aa0?, 0x0?})
        /usr/local/go/src/reflect/value.go:370 +0xbc
github.com/graph-gophers/graphql-go/internal/exec.execFieldSelection.func2(0x0?, {0x6a14f30?, 0xc015614480?}, 0xc00d3005a0, 0xc011473c00, 0xc010e19ec0, {0x6a14f68?, 0xc015614630})
        /home/nonsense/go/pkg/mod/github.com/graph-gophers/graphql-go@v1.3.0/internal/exec/exec.go:211 +0x4c6
github.com/graph-gophers/graphql-go/internal/exec.execFieldSelection({0x6a14f30, 0xc015614480}, 0xc000f31c00, 0x0?, 0xc011473c00, 0x0?, 0x1)
        /home/nonsense/go/pkg/mod/github.com/graph-gophers/graphql-go@v1.3.0/internal/exec/exec.go:231 +0x1ce
github.com/graph-gophers/graphql-go/internal/exec.(*Request).execSelections.func1(0xc011473c00)
        /home/nonsense/go/pkg/mod/github.com/graph-gophers/graphql-go@v1.3.0/internal/exec/exec.go:81 +0x1b8
created by github.com/graph-gophers/graphql-go/internal/exec.(*Request).execSelections
        /home/nonsense/go/pkg/mod/github.com/graph-gophers/graphql-go@v1.3.0/internal/exec/exec.go:77 +0x1d0

context: context.Background.WithCancel.WithCancel.WithValue(type string, val <not Stringer>).WithDeadline(2023-11-02 08:32:11.950743271 -0400 EDT m=+5850.009873342 [989.185705ms])
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x2257b97]

goroutine 6735815 [running]:
github.com/graph-gophers/graphql-go/internal/exec.(*Request).handlePanic(0xc000f31c00, {0x6a14f30, 0xc015614480})
        /home/nonsense/go/pkg/mod/github.com/graph-gophers/graphql-go@v1.3.0/internal/exec/exec.go:33 +0x77
panic({0x4f77820, 0x8e0aab0})
        /usr/local/go/src/runtime/panic.go:884 +0x213
github.com/graph-gophers/graphql-go/internal/exec.execFieldSelection.func2.1()
        /home/nonsense/go/pkg/mod/github.com/graph-gophers/graphql-go@v1.3.0/internal/exec/exec.go:188 +0x96
panic({0x4f77820, 0x8e0aab0})
        /usr/local/go/src/runtime/panic.go:884 +0x213
github.com/filecoin-project/boost/lib/mpoolmonitor.(*MpoolMonitor).MsgExecElapsedEpochs(0xc00c9b86c0, {0x6a14f68, 0xc015614630}, {{0xc19c83cab0?, 0x1?}})
        /home/nonsense/boost/lib/mpoolmonitor/mpoolmonitor.go:196 +0x185
github.com/filecoin-project/boost/gql.(*dealResolver).message(0xc00eda4800, {0x6a14f68?, 0xc015614630?}, 0xc000b6f660?, {0x881855?, 0x50efec0?, 0x50efec0?})
        /home/nonsense/boost/gql/resolver.go:620 +0x588
github.com/filecoin-project/boost/gql.(*dealResolver).Message(0xc00eda4800, {0x6a14f68?, 0xc015614630?})
        /home/nonsense/boost/gql/resolver.go:574 +0x48
reflect.Value.call({0x540b9a0?, 0xc00eda4800?, 0x8205f6?}, {0x5487e55, 0x4}, {0xc00d3005d0, 0x1, 0x87c72e?})
        /usr/local/go/src/reflect/value.go:586 +0xb0b
reflect.Value.Call({0x540b9a0?, 0xc00eda4800?, 0xc000130720?}, {0xc00d3005d0?, 0x5469aa0?, 0x0?})
        /usr/local/go/src/reflect/value.go:370 +0xbc
github.com/graph-gophers/graphql-go/internal/exec.execFieldSelection.func2(0x0?, {0x6a14f30?, 0xc015614480?}, 0xc00d3005a0, 0xc011473c00, 0xc010e19ec0, {0x6a14f68?, 0xc015614630})
        /home/nonsense/go/pkg/mod/github.com/graph-gophers/graphql-go@v1.3.0/internal/exec/exec.go:211 +0x4c6
github.com/graph-gophers/graphql-go/internal/exec.execFieldSelection({0x6a14f30, 0xc015614480}, 0xc000f31c00, 0x0?, 0xc011473c00, 0x0?, 0x1)
        /home/nonsense/go/pkg/mod/github.com/graph-gophers/graphql-go@v1.3.0/internal/exec/exec.go:231 +0x1ce
```

**Comment by ischasny** [comment]
Added a small fix: https://github.com/filecoin-project/boost/pull/1817 - what are the steps to reproduce the issue?
