### ISSUE TITLE
flaky test due to closing a closed channel

### ISSUE THREAD

**Issue by nonsense** [filecoin-project/boost#291]
```
    test_framework.go:537: Deal 2 state: client:StorageDealSealing 
    test_framework.go:537: Deal 2 state: client:StorageDealSealing 
    test_framework.go:532: complete &{bafyreic6abouidkxlclnnptfiicsnxw2f6vtxzurpda66ndbx66regyb6a 7  0xc0035c9158 t01000 0xc002f341c0 baga6ea4seaqf7npmdvfsigmwqawikmoakqf45bkxd4kjhwzdo7lfpc6a2uulcoi 8323072 62500000 519609 2 2022-02-25 12:08:40.228302659 +0000 UTC false 12D3KooWA5dYFgQzXgGhBYehEbuNa5Duv2FCfvW2uabexGbxvAad-12D3KooWAATxNcpeRQFF2MP6Xs7iLTBn4xAVnRm57RBbhRs2Qd9q-1645790840278205973 0xc00263ff10}
2022-02-25T12:12:08.399Z	INFO	boost-provider	storagemarket/provider.go:359	storage provider: stopping
2022-02-25T12:12:08.399Z	INFO	boost-provider	storagemarket/provider.go:372	stopping provider event loop
2022-02-25T12:12:08.400Z	INFO	boost-provider	storagemarket/provider_loop.go:119	provider event loop complete
2022-02-25T12:12:08.400Z	INFO	boost-provider	storagemarket/provider.go:374	provider shutdown complete
panic: close of closed channel

goroutine 5321 [running]:
github.com/filecoin-project/lotus/journal/fsjournal.(*fsJournal).Close(0xc002787c20)
	/go/pkg/mod/github.com/filecoin-project/lotus@v1.14.0-rc6.0.20220223145324-b7081dc4f67c/journal/fsjournal/fs.go:87 +0x25
github.com/filecoin-project/lotus/node/modules.OpenFilesystemJournal.func1({0xc002acfd40, 0x3140dcf})
	/go/pkg/mod/github.com/filecoin-project/lotus@v1.14.0-rc6.0.20220223145324-b7081dc4f67c/node/modules/services.go:256 +0x22
go.uber.org/fx/internal/lifecycle.(*Lifecycle).Stop(0xc00410c7e0, {0x3658598, 0xc00005a070})
	/go/pkg/mod/go.uber.org/fx@v1.9.0/internal/lifecycle/lifecycle.go:86 +0x139
go.uber.org/fx.withTimeout.func1()
	/go/pkg/mod/go.uber.org/fx@v1.9.0/app.go:600 +0x31
created by go.uber.org/fx.withTimeout
	/go/pkg/mod/go.uber.org/fx@v1.9.0/app.go:600 +0xe5
FAIL	github.com/filecoin-project/boost/itests	557.476s
FAIL
```

https://app.circleci.com/pipelines/github/filecoin-project/boost/1219/workflows/94ec12d8-e609-4f92-9aa7-9df2211fc584/jobs/6709

**Comment by dirkmc** [comment]
Closing as I believe this should be fixed now that we no longer run tests against the devnet
