### ISSUE TITLE
boost crashes, when lotus-miner is restarted due to nil ptr dereference

### ISSUE THREAD

**Issue by nonsense** [filecoin-project/boost#965]
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0xa802bb]

goroutine 37040 [running]:
github.com/filecoin-project/go-jsonrpc.(*RPCConnectionError).Error(0x4601fa0?)
        /root/code/pkg/mod/github.com/filecoin-project/go-jsonrpc@v0.1.8/errors.go:15 +0x1b
github.com/filecoin-project/boost/storagemarket.(*Provider).AddPieceToSector(_, {_, _}, {{0xa8, 0xc4, 0x5, 0xb2, 0x6f, 0x48, 0x46, ...}, ...}, ...)
        /root/boost/storagemarket/provider.go:598 +0x482
github.com/filecoin-project/boost/storagemarket.(*Provider).addPiece(0xc01890c1e0, {0x461a980, 0xc000876640}, {0x460ff10, 0xc020ef0d20}, 0xc016d74c40)
        /root/boost/storagemarket/deal_execution.go:538 +0x645
github.com/filecoin-project/boost/storagemarket.(*Provider).execDealUptoAddPiece(0xc01890c1e0, {0x461a980, 0xc000876640}, 0xc016d74c40, 0xc01845ca80)
        /root/boost/storagemarket/deal_execution.go:197 +0x610
github.com/filecoin-project/boost/storagemarket.(*Provider).execDeal(0xc01890c1e0, 0xc016d74c40, 0xc01845ca80)
        /root/boost/storagemarket/deal_execution.go:108 +0x3c5
github.com/filecoin-project/boost/storagemarket.(*Provider).runDeal(0xc01890c1e0, 0xc016d74c40, 0xc01845ca80)
        /root/boost/storagemarket/deal_execution.go:51 +0x274
github.com/filecoin-project/boost/storagemarket.(*Provider).startDealThread.func1()
        /root/boost/storagemarket/provider_loop.go:545 +0xaa
created by github.com/filecoin-project/boost/storagemarket.(*Provider).startDealThread
        /root/boost/storagemarket/provider_loop.go:538 +0xbc
```

**Comment by nonsense** [comment]
We are running a patched version of `go-jsonrpc` for now. Will re-open if this happens again.
